#!/usr/bin/env python3
"""Select compact fresh replay records without dropping mathematical binaries.

This helper only inventories files: it does not copy them or certify arithmetic.
A complete integrated selection is bound to the frozen candidate manifest. The
--allow-incomplete option is solely for inspecting earlier component trials.
"""
from pathlib import Path, PurePosixPath
import argparse,hashlib,json,os,stat

V3='2026-09-13_primitive_357_dependency_closed_release_v3'
P5='2026-09-13_p5_literal_c_obstruction_dependency_closure_v1'
RANK='2026-09-13_corrected66_predyadic_and_p2_place2_dependency_closure_v1'
CACHE_COMPONENTS={'sage_cache','sage-cache','sage_home','dot_sage','__pycache__'}
# Most specific prefix wins. These are inspected copy operations, not a rule
# that directories called "repository" are disposable.
COPY_PREFIXES=[
 ('prior/work/v3_audit/sage_replay/repository','evidence/v3/repository'),
 (f'prior/work/v3_audit/extracted/{V3}/repository','evidence/v3/repository'),
 (f'prior/work/p5_archive_audit/extracted/{P5}/repository','evidence/p5/repository'),
 (f'prior/work/rank_closure_audit/extracted/{RANK}/repository','evidence/rank/repository'),
 ('prior/work/p5_archive_audit/arithmetic/repository','evidence/p5/repository'),
 ('sectors/v3','evidence/v3'),
 ('prior/work','audit/work'),
]
EXACT_COPIES={
 'prior/check_s4_relation.py':'audit/work/integration_prior/check_s4_relation.py',
 'prior/check_five_saturation.py':'audit/work/integration_prior/check_five_saturation.py',
}
# The only persisted native tool generated by the inspected replay is the
# fresh C point counter. Its C source is in the sealed candidate; its complete
# numerical output is retained. No .bin/.sobj rule is used.
NATIVE_TOOL_PATHS={'sectors/hecke_foundations/ordinary_counts'}
KNOWN_ALIASES={'prior/work/p5_archive_audit/arithmetic/repository','prior/work/v3_audit/runtime/pari-2.15.4/gp'}
NATIVE_MAGIC={b'\x7fELF',b'\xfe\xed\xfa\xce',b'\xce\xfa\xed\xfe',b'\xfe\xed\xfa\xcf',b'\xcf\xfa\xed\xfe',b'\xca\xfe\xba\xbe',b'\xbe\xba\xfe\xca',b'\xca\xfe\xba\xbf',b'\xbf\xba\xfe\xca'}

def need(ok,message):
 if not ok:raise RuntimeError(message)
def sha(path):
 h=hashlib.sha256()
 with path.open('rb') as f:
  for data in iter(lambda:f.read(1048576),b''):h.update(data)
 return h.hexdigest()
def load_json(path):
 def unique(rows):
  out={}
  for k,v in rows:
   need(k not in out,'Duplicate JSON key: '+k);out[k]=v
  return out
 return json.loads(path.read_text(),object_pairs_hook=unique)
def original_path(logical):
 if logical in EXACT_COPIES:return EXACT_COPIES[logical]
 for prefix,target in COPY_PREFIXES:
  if logical==prefix or logical.startswith(prefix+'/'):
   suffix=logical[len(prefix):].lstrip('/');return target+('/'+suffix if suffix else '')
 return None

def select_final_artifacts(replay_root,candidate_root,component='integrated',require_completed=True):
 replay=Path(replay_root).resolve();candidate=Path(candidate_root).resolve()
 need(replay.is_dir() and candidate.is_dir(),'Replay and candidate roots must exist')
 need(component in {'integrated','prior','sectors','rank_local'},'Unsupported component layout')
 manifest_path=candidate/'RELEASE_MANIFEST.json';manifest=load_json(manifest_path);manifest_sha=sha(manifest_path)
 need(manifest.get('schema')=='primitive357_verified_release_manifest_v1','Wrong candidate manifest schema')
 lookup={};names=[]
 for row in manifest['files']:
  s=row['path'];p=PurePosixPath(s)
  need(not p.is_absolute() and '..' not in p.parts and str(p)==s and s not in lookup,'Unsafe/duplicate candidate path')
  lookup[s]=row;names.append(s)
 need(names==sorted(names),'Unsorted candidate manifest')
 if require_completed:
  need(component=='integrated','A component trial is not a final integrated run')
  result=load_json(replay/'REPLAY_RESULT.json')
  need(result['status']=='PASS_FRESH_INTEGRATED_REPLAY','Integrated run is not complete')
  need(result['input_manifest']['manifest_sha256']==manifest_sha,'Replay/candidate manifest identity mismatch')
  need(result['input_manifest']['files']==len(lookup),'Replay/candidate file-count mismatch')
 selected=[];excluded=[];problems=[]
 for directory,dirs,files in os.walk(replay,followlinks=False):
  directory=Path(directory)
  # Directory aliases are runtime plumbing; never traverse or copy them.
  for name in list(dirs):
   p=directory/name;rel=p.relative_to(replay).as_posix()
   if p.is_symlink():
    logical=rel if component=='integrated' else component+'/'+rel
    need(logical in KNOWN_ALIASES,'Unclassified directory alias; review before selecting: '+rel)
    dirs.remove(name);excluded.append({'path':rel,'reason':'runtime_directory_alias','target':os.readlink(p)})
   elif name in CACHE_COMPONENTS or (component=='integrated' and rel=='runtime-cache'):
    dirs.remove(name);excluded.append({'path':rel+'/', 'reason':'software_cache_directory'})
  for name in files:
   p=directory/name;rel=p.relative_to(replay).as_posix();logical=rel if component=='integrated' else component+'/'+rel
   if p.is_symlink():
    need(logical in KNOWN_ALIASES,'Unclassified file alias; review before selecting: '+rel)
    excluded.append({'path':rel,'reason':'runtime_file_alias','target':os.readlink(p)});continue
   mode=p.stat().st_mode
   need(stat.S_ISREG(mode),'Unexpected nonregular replay artifact: '+rel)
   if p.suffix in {'.pyc','.pyo'} or p.name=='.DS_Store':
    excluded.append({'path':rel,'reason':'compiled_python_or_os_metadata'});continue
   before=p.stat();digest=sha(p);after=p.stat()
   need((before.st_size,before.st_mtime_ns)==(after.st_size,after.st_mtime_ns),'Replay artifact changed during selection: '+rel)
   row={'path':rel,'bytes':after.st_size,'sha256':digest}
   original=original_path(logical);old=lookup.get(original)
   if old and old['bytes']==row['bytes'] and old['sha256']==digest:
    excluded.append(dict(row,reason='identical_sealed_input_copy',candidate_path=original));continue
   if logical in NATIVE_TOOL_PATHS:
    with p.open('rb') as f:magic=f.read(4)
    need(magic in NATIVE_MAGIC or magic[:2]==b'MZ','Expected native point-counter executable: '+rel)
    excluded.append(dict(row,reason='fresh_compiled_software',source_candidate_path='audit/work/hecke_foundations/scripts/independent_ordinary_counts.c',numerical_output='sectors/hecke_foundations/independent_ordinary_counts.txt'));continue
   # Never discard GP/Sage binary mathematical objects on extension alone.
   with p.open('rb') as f:magic=f.read(4)
   if p.suffix not in {'.bin','.sobj'} and (magic in NATIVE_MAGIC or magic[:2]==b'MZ'):
    problems.append('Unclassified native software; review explicitly before selecting: '+rel)
   if 'repository' in PurePosixPath(logical).parts and original is None:
    problems.append('Unmapped repository copy; review before selecting: '+rel)
   if original:
    row['candidate_path']=original
    row['retention_reason']='changed_copy_or_generated_artifact' if old else 'new_artifact_inside_known_copy'
   else:row['retention_reason']='generated_artifact_or_execution_provenance'
   selected.append(row)
 need(not problems,'\n'.join(problems))
 selected.sort(key=lambda r:r['path']);excluded.sort(key=lambda r:r['path'])
 need(len({r['path'] for r in selected})==len(selected),'Duplicate selected artifact')
 return {'schema':'primitive357_final_artifact_selection_v1','inspection_only':not require_completed,'component':component,'candidate_manifest_sha256':manifest_sha,'candidate_file_count':len(lookup),'selected_file_count':len(selected),'selected_bytes':sum(r['bytes'] for r in selected),'files':selected,'excluded':excluded,'policy':{'unchanged_inputs':'Only exact size/SHA equality to a named frozen candidate file permits original-copy exclusion. Changed/new files in cloned repositories are retained.','mathematical_binaries':'All generated .bin and .sobj objects retained; no blanket binary/extension exclusion.','logs':'Every new/changed execution log retained outside explicitly excluded software-cache directories. Unchanged archived logs are referenced by candidate path/hash.','native_tools':'Only the inspected ordinary_counts compiler output is excluded; unknown native files demand review.','symlinks':'Aliases are recorded rather than followed; all known aliases point to an already traversed repository or declared software runtime.','scope':'Selection and provenance only; the top-level fresh replay establishes the arithmetic status. Transient worker streams deleted before completion cannot be recovered by this selector.'}}

def main():
 p=argparse.ArgumentParser(description=__doc__);p.add_argument('--replay-root',required=True,type=Path);p.add_argument('--candidate-root',required=True,type=Path);p.add_argument('--output',required=True,type=Path)
 p.add_argument('--component',choices=['integrated','prior','sectors','rank_local'],default='integrated');p.add_argument('--allow-incomplete',action='store_true');a=p.parse_args()
 need(not a.output.exists(),'Refuse to overwrite an artifact selection')
 need(a.replay_root.resolve() not in a.output.resolve().parents,'Write the selection outside the replay tree')
 data=select_final_artifacts(a.replay_root,a.candidate_root,a.component,not a.allow_incomplete)
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(data,indent=2)+'\n')
 print(json.dumps({k:data[k] for k in ('inspection_only','selected_file_count','selected_bytes','candidate_manifest_sha256')}))
if __name__=='__main__':main()
